repos:
  - repo: local
    hooks:
      - id: local-build
        name: Locally build
        description: A local make file to always build and test locally
        entry: make build
        files: '\.go$'
        language: 'system'